import { useState, useEffect } from 'react';
import { motion, AnimatePresence, useMotionValue, useTransform } from 'framer-motion';
import { useProgress } from '@react-three/drei';
import { JetScene } from './components/JetScene';
import { CustomCursor } from './components/CustomCursor';
import { FrameSequence } from './components/FrameSequence';

export default function App() {
  const [isLoading, setIsLoading] = useState(true);
  const { active, progress } = useProgress();
  
  // Motion value to track the scroll offset generated by ScrollControls inside the Canvas
  const scrollOffset = useMotionValue(0);
  
  // Cloud background: visible in hero (0-0.10), fades out for dark sections (0.10-0.20),
  // stays hidden, then fades back in for sketchbook/CTA (0.70-0.80)
  const cloudOpacity = useTransform(scrollOffset, [0, 0.10, 0.20, 0.70, 0.80], [1, 1, 0, 0, 1]);
  
  // Dark overlay: fades in over clouds for dark travel sections (0.15-0.25), fades out for sketchbook (0.65-0.75)
  const cloudDarkOverlay = useTransform(scrollOffset, [0.15, 0.25, 0.65, 0.75], [0, 0.85, 0.85, 0]);
  
  // Frame sequence: appears at travel section (0.20-0.28), disappears before how-it-works (0.38-0.44)
  const frameOpacity = useTransform(scrollOffset, [0.20, 0.28, 0.38, 0.44], [0, 1, 1, 0]);

  useEffect(() => {
    // Wait for both the initial timer (minimum loading time for effect) and 3D assets to load
    const timer = setTimeout(() => {
      if (progress === 100 || !active) {
        setIsLoading(false);
      }
    }, 2000);
    
    if (progress === 100 && !active) {
      setTimeout(() => setIsLoading(false), 500); // Small buffer
    }

    return () => clearTimeout(timer);
  }, [progress, active]);

  return (
    <div className="w-full h-screen bg-black overflow-hidden relative font-sans">
      <CustomCursor />
      
      {/* FIXED BACKGROUNDS (Behind Canvas) */}
      <div className="absolute inset-0 z-0 pointer-events-none w-full h-full">
         
         {/* Persistent Cloud Background with Dynamic Overlay */}
         <motion.div 
            style={{ opacity: cloudOpacity }}
            className="absolute inset-0 w-full h-full bg-cover bg-center"
            initial={{ backgroundImage: 'url(/new_bg.png)' }}
         >
            <div className="absolute inset-0 bg-white/20 backdrop-blur-[1px]"></div>
            <div className="absolute bottom-0 left-0 w-full h-[35vh] bg-gradient-to-t from-white/95 via-white/50 to-transparent"></div>
            {/* Dark gradient overlay for later sections */}
            <motion.div 
              style={{ opacity: cloudDarkOverlay }}
              className="absolute inset-0 bg-gradient-to-b from-black/80 via-black/90 to-black/95"
            ></motion.div>
         </motion.div>

         {/* Phase 3 Background: Window Shade Reveal (Canvas frame sequence) */}
         <motion.div 
            style={{ opacity: frameOpacity }}
            className="absolute inset-0 w-full h-full"
         >
            <FrameSequence scrollOffset={scrollOffset} />
            {/* Dark gradient overlay (10% to 40% black) for text readability */}
            <div className="absolute inset-0 bg-gradient-to-b from-black/10 to-black/40"></div>
         </motion.div>
      </div>

      {/* Preloader */}
      <AnimatePresence>
        {isLoading && (
          <motion.div 
            initial={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 1.5, ease: "easeInOut" }}
            className="absolute inset-0 z-[100] flex items-center justify-center bg-black"
          >
            <motion.div 
              className="flex flex-col items-center"
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ duration: 0.8, ease: "easeOut" }}
            >
              <h1 className="text-4xl md:text-5xl font-light text-white tracking-[0.2em] uppercase mb-4 relative overflow-hidden flex items-center gap-4">
                 <svg width="40" height="40" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="text-white">
                    <path d="M22 2L2 12L9 14.5L16 8L11 16L18 19L22 2Z" fill="currentColor"/>
                 </svg>
                 LuxFly
              </h1>
              <div className="w-48 h-[2px] bg-white/20 rounded-full overflow-hidden relative">
                <motion.div 
                  initial={{ width: 0 }}
                  animate={{ width: "100%" }}
                  transition={{ duration: 2.5, ease: "easeInOut" }}
                  className="absolute left-0 top-0 h-full bg-[#e9ecf0]"
                />
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* The 3D Canvas Context (Now handles ScrollControls and OverlayHTML) */}
      <div className="absolute inset-0 w-full h-full z-10">
         <JetScene isLoading={isLoading} scrollOffset={scrollOffset} />
      </div>

    </div>
  );
}
